### ISSUE TITLE
Lite Version Not working

### ISSUE THREAD

**Issue by Dreded** [Voljega/ExoDOSConverter#100]
In Windows 10 exodos_lite does not download games etc, they fail...
'''
<WARNING> C:\Games\eXoDOS_Lite\eXo\eXoDOS\1000 Miler (1987).zip not found
  Error <class 'TypeError'> while converting game 1000mile
'''
However if I open launchbox and install the game first it then works.

**Comment by Voljega** [comment]
yes because the launchbox version is using torrent to download the missing games, whereas this tool was using https://the-eye.eu/ and as you can see going on the homepage they were down for a long time

as soon as they add the collection back, it should work again

**Comment by Voljega** [comment]
The eye is back, should be ok know ?
