### ISSUE TITLE
Dies at the end when trying to convert the complete collection

### ISSUE THREAD

**Issue by chr0m** [Voljega/ExoDOSConverter#104]
I get the error below right at the end. I've tried it twice now for the same result. The second time I ran in admin mode.

It doesn't complete the TDL setup and I only end up with these files in the TDL_VHD folder:
files
FILES.IDX
games
TITLES.IDX
utils

I was able to get the rest of the files from the top 300 image, but a lot of the games are running missing.bat instead of 1_start.bat.

Has this tool been abandoned?

```
  All games indexed
  Moving cd folder to tdlprocessed, this might take a while ...
  Moving floppy folder to tdlprocessed, this might take a while ...
  Moving bootdisk folder to tdlprocessed, this might take a while ...
Exception ignored in thread started by: <bound method ExoConverter.convertGames of <exoconverter.ExoConverter object at 0x0000028D3BEE6B80>>
Traceback (most recent call last):
  File "exoconverter.py", line 78, in convertGames
  File "exoconverter.py", line 237, in __postConversion__
  File "shutil.py", line 737, in rmtree
  File "shutil.py", line 610, in _rmtree_unsafe
  File "shutil.py", line 610, in _rmtree_unsafe
  File "shutil.py", line 619, in _rmtree_unsafe
  File "shutil.py", line 617, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'D:\\Utils\\eXoConverter 0.9.2-beta\\data\\mister\\distro\\utils\\configs'
```

**Comment by Voljega** [comment]
Does it happen with a smaller selection ?
Maybe the disk is full near the end and the converter can't access to the disk anymore ?

**Comment by chr0m** [comment]
Hey, thanks for the response. The disk definitely isn't full, there's still a few hundred GB free :)

I'll try on a smaller set. I'm trying to figure out why some games are running missing.bat, while others are working. If TDL finds a folder matching the zip file name in the cache folder it should just use that right? From what I can tell the FILES.IDX and TITLES.IDX have generated correctly.

**Comment by chr0m** [comment]
Deleted the distro folder and reran and it finished successfully!
