### ISSUE TITLE
0.9.3-beta not able to find my exodos or exowin3x collection

### ISSUE THREAD

**Issue by mdlarussa** [Voljega/ExoDOSConverter#106]
Cannot proceed past collection folder...
D:\eXoDOS is not a directory, doesn't exist, or is not a valid eXo collection directory
Did you install the collection with setup.bat beforehand ?

Reran setup.bat and tried again, but no luck.
Same problem on windows side...
D:\eXoWin3x is not a directory, doesn't exist, or is not a valid eXo collection directory
Did you install the collection with setup.bat beforehand ?

Also -  App title still says 0.9.2-beta when running the 0.9.3-beta version

**Comment by mdlarussa** [comment]
What exactly is the script looking for to validate the install?

**Comment by Voljega** [comment]
Hello I'll have a look later in the week

**Comment by mdlarussa** [comment]
![image](https://user-images.githubusercontent.com/6157963/182643177-c091ae16-657d-4fe7-8bef-eb5688c8602f.png)
Was able to get the Win3x one working, but DOS still a no-go.  Reran setup, still can't find whatever it needs.

**Comment by Voljega** [comment]
Your installation doesn't seem to be valid, mine looks like that:
![image](https://user-images.githubusercontent.com/1405681/182773251-224af90e-c197-49d5-93dd-de7e636002b8.png)

Look into the eXoDOS folder ?

I think the specific thing you're missing is the eXo folder you can see in my installation, which itseld contains an eXoDOS folder.

Pretty sure your setup.bat failed before the end, it seems XODOSMetadata.zip was not decompressed at all.

**Comment by Voljega** [comment]
no feedback from user
