### ISSUE TITLE
Missing pack_ver.txt and launch.bat

### ISSUE THREAD

**Issue by eobet** [Voljega/ExoDOSConverter#107]
I ran the converter with the MiSTer settings and created a VHD for it, copied the cd/floppy to the Mister, mounted the VHD (with a boot VHD as well) but now see error messages about missing pack_ver.txt and I also notice that there's no launch.bat...

How do you repair issues like that? Everything is already converted now and over on the Mister...

(Also, yes, I realize this is more a discussion than an issue, but I see no discussion tab in this repository. Is there a better place to ask questions like this?)

**Comment by Voljega** [comment]
Hello, well I wasn't aware of the discussions tab either !
Here is ok for questions.

I don't know much about MiSTeR unfortunately, but @flynnsbit should be able to help you

**Comment by eobet** [comment]
Ok, so for anyone else who run into this, here's what I had to do to get it working:

1. Get the pack_ver.txt file from [here](https://github.com/flynnsbit/Top300_updates/blob/main/pack_ver.txt) and manually place it in the C: VHD.
2. Ignore the missing launch.bat and instead manually edit the TDL.ini to point out the files and games folders on D:

After that, it seems to work as reasonably as you'd expect it to. 🤓

**Comment by Voljega** [comment]
Thank you very much for the report and solution
