### ISSUE TITLE
Namegame is changed in export 

### ISSUE THREAD

**Issue by toniosj** [Voljega/ExoDOSConverter#112]
Test: eXoDOS v6
eXoConverter 0.9.4 

Conversion Type: Batocera
Long Folder Names: ON

eXodos Original File: **James Bond 007 - The Stealth Affair (1990).zip**

Folder generated: **007 James Bond - The Stealth Affair (1990).pc**

Why does ExoDOSConverter change the gamename? Could you add an option to use original exodos filename?

I need to use same file name to scrape games correctly with ScreenScraper: [https://www.screenscraper.fr/gameinfos.php?gameid=156962&action=onglet&zone=gameinfosroms](https://www.screenscraper.fr/gameinfos.php?gameid=156962&action=onglet&zone=gameinfosroms)

Thanks!!

**Comment by Voljega** [comment]
I will have a look at it, most likely a discrepancy between metada / folder
/ files naming in the collection

**Comment by Voljega** [comment]
I fixed the folder name generation for this, kind of manually but can't do much about the bad title in metadata

alternatively you can fix the metadata manually in `eXo\eXoDOS\Data\Platforms\MS-DOS.xml`, edit the Title xml tag to be correct:
`<Title>007 James Bond: The Stealth Affair</Title>`

**Comment by Voljega** [comment]
If you have any other similar issues, open a new issue for them
