### ISSUE TITLE
eXoWin3x v2 errors

### ISSUE THREAD

**Issue by toniosj** [Voljega/ExoDOSConverter#118]
I've processed eXoWin3x v2 using your last alpha eXoConverter-0.9.5-db-pure-alpha6 with rezip for DosBox-Pure check ON.

I attach log files.

[errors.txt](https://github.com/Voljega/ExoDOSConverter/files/13534012/errors.txt)
[error_log.txt](https://github.com/Voljega/ExoDOSConverter/files/13534013/error_log.txt)

**Comment by Voljega** [comment]
actually most of these are known issues, see https://github.com/Voljega/ExoDOSConverter/wiki/Known-issues:-eXoWin3x-v2

can't reproduce the error for DejaVuII
