### ISSUE TITLE
DOSbox-Pure conversion not fully-functional.

### ISSUE THREAD

**Issue by NightSprinter** [Voljega/ExoDOSConverter#126]
I just want to start off by saying I appreciate adding support for DOSbox-pure in your converter.  Unfortunately, it doesn't always result in RetroArch being able to detect the game properly (if at all).  I've tried using both the Batocera and Retrobat options in the converter.  Certain games I want to play, such as MK2, Super Street Fighter II Turbo, or X-Men: Children of the Atom do not seem to get added to a playlist in RetroArch at ALL.  Other times,  content import will give the correct name to an imported zip file (such as Williams Arcade Classics), but then point to the wrong executable file in the archive (such as for Robotron) which results in the game just not working.

Sometimes, an "entry" both has the wrong name and points to a file that shouldn't be pointed to.  It's just frustrating, as I have games I want to convert for that core, so I can play these games on the go via my Steam Deck.

**Comment by Voljega** [comment]
In retroarch configuration for dosbox-pure core, you need to allow dosbox-pure to use dosbox.cfg and save this configuration

**Comment by bloodykean** [comment]
For Dosbox Pure specific i would suggest some adjustments:

1. I would include AUTOBOOT.DBP in the root folder of the zip (dosz) file that points to the executable that needs to be run. For example "C:\DOSBOX.BAT" or "C:\run.bat" or whatever executable you want to execute.

3. The second thing would be to include the JCHOICE.EXE file. That is a custom made CHOICE dos command, that supports the use of a controller for selection in the run.bat files in the eXoDos ecosystem. I could send you the file if you wish. For this matter the run.bat files must be changed and in the file the line with the command CHOICE must be changed to JCHOICE.

4. The [autoexec] section of the conf file to be copied to the separate file DOSBOX.BAT, that the execution is separated. That is documented in the wiki of Dosbox Pure.

5. For better support by Dosbox Pure i've made also some "opt" files, that are used by retroarch for specific settings for the games. The files can be used for settings like "memsize", "cycles", "core". The naming convention is the same as the name of the game file. The opt files can be than copied to the folder where the settings for Dosbox Pure are saved. Than by starting the game it uses this setting file and the conf files are than not needed. 

By the way. Thank you for your time and for your work.

**Comment by Voljega** [comment]
@bloodykean If I'm not mistaken though, points 1 3 and 4 are already handled by the use of the dosbox.cfg bu lr-dosbox-pure through the correct retroarch parameter

Point 2 is a nice touch, I'll try adding it when I will able to resume work on the converter (not before a few weeks)

**Comment by bloodykean** [comment]
@Voljega it's ok. You find the JCHOICE file in the attachment. Rename it to JCHOICE.EXE.
![JCHOICE](https://github.com/Voljega/ExoDOSConverter/assets/49002344/060a68c1-dfc0-437f-b426-c5e1b7c6a0d9)

**Comment by bloodykean** [comment]
@Voljega if you need the JCHOICE file, then please contact me.

**Comment by Voljega** [comment]
Yes please add it here

**Comment by bloodykean** [comment]
For the 1 3 and 4 i made a powershell script that does all the hard work for me. 
[JCHOICE.zip](https://github.com/Voljega/ExoDOSConverter/files/14449713/JCHOICE.zip)
The file is zipped and you can test it in dosbox. Thank you for you work.

**Comment by Voljega** [comment]
Thank you for the file

My point for 1 3 and 4 is they are useless if you activate the retroarch dosbox-pure core parameter mentioned in my first response in this thread

**Comment by bloodykean** [comment]
I know that. But i tried all sort of combinations for the automatic settings that the conf file offers and that didn’t work for me or there was no transparency that the setting were taken. I know for sure that dosbox pure uses for the cycles the steps that are given. You cannot use like 10000 cycles. You must set them to like  13400. I found that in the documentation:https://docs.libretro.com/library/dosbox_pure/ 
Maybe i am wrong and i must test some more. 
Thank you for your help.

**Comment by Voljega** [comment]
JCHOICE file added in today's release
and I added how to configure dosbox-pure in the README to do what you mentioned
