### ISSUE TITLE
eXoDOS directory not recognized 

### ISSUE THREAD

**Issue by aXeHndl** [Voljega/ExoDOSConverter#128]
I am trying to use eXoDOSConverter 0.9.6 to convert eXoDOS v6 to RetroPie. I moved a fresh copy of eXoDOS to an external drive and ran setup.bat. When I run the gui in either Windows or on the Pi, I get a message that says the directory does not exist or it’s not a valid eXoDOS directory. The directory is there full of zip files and there is a !dos subdirectory. What am I doing wrong?

**Comment by Voljega** [comment]
If the zip files are still there, the setup.bat didn't work all the way

**Comment by aXeHndl** [comment]
Perhaps the install process has changed. The Setup.bat appears to run without error. When I run Lauchbox from the drive’s root directory, it displays 7000+ titles. When I select one, I am asked if I want to install it. Only if I select Y does it create an unzipped folder in eXo/eXoDOS. Even with four games “installed” in this manner, I still get the missing/invalid directory message. Should I unzip all of the game folders? Would it be help to send a copy of the Setup.bat I’m using?

**Comment by Voljega** [comment]
No I thought you meant the big zips at the root of the exodosfolder.
Can you include a screen cap ? most likely you are not selecting the root of the exodos folder

**Comment by aXeHndl** [comment]
Will this screen capture work? Also, thanks for looking into this.

**Comment by Voljega** [comment]
It seems you forgot to include the screen capture

**Comment by aXeHndl** [comment]
Strange. It was on my sent email. Here is another try.On Feb 22, 2024, at 3:30 PM, Voljega ***@***.***> wrote:﻿
It seems you forgot to include the screen capture

**Comment by aXeHndl** [comment]
![eXoDOS Converter Capture](https://github.com/Voljega/ExoDOSConverter/assets/160696989/6ecb5a33-f2d4-4864-971c-dc441e4148d3)

**Comment by Voljega** [comment]
So as I said your issue here is you should select the root of the collection, not the eXo\eXoDOS folder ...
In your case this would be H: although it would be better I guess if the root of the collection was at least in a directory, but try with H:

**Comment by aXeHndl** [comment]
Thank, that worked. Also, thank you for being patient with a new user. Now I’m trying to figure out RetroPie. I’ve read that placing a period before the directory name hides it from the front end, so I don’t see subdirectories. Is there an option in eXoDOS converter to automatically do that or is there a better way to accomplish the same thing? On Feb 23, 2024, at 1:54 AM, Voljega ***@***.***> wrote:﻿
So as I said your issue here is you should select the root of the collection, not the eXo\eXoDOS folder ...
In your case this would be H: although it would be better I guess if the root of the collection was at least in a directory, but try with H:

**Comment by Voljega** [comment]
I can't say that the retropie conversion is well tested in any wat, there
is an issue for it with many fix to do but I haven't been around it.

Can't say I know much about it either, but on a personal.not it seems the
newer distributions like batocera are much more easier to use

**Comment by aXeHndl** [comment]
Thanks. I’ll look into Bactocera.On Feb 23, 2024, at 9:41 AM, Voljega ***@***.***> wrote:﻿
I can't say that the retropie conversion is well tested in any wat, there

is an issue for it with many fix to do but I haven't been around it.



Can't say I know much about it either, but on a personal.not it seems the

newer distributions like batocera are much more easier to use
