### ISSUE TITLE
Is it compatible with dosbox-staging?

### ISSUE THREAD

**Issue by Crazy-bat11** [Voljega/ExoDOSConverter#132]
If not, could you consider implementing an option to also generate a conf file compatible with dosbox-staging?
Anyway, great project!

**Comment by Voljega** [comment]
It should work with dosbox-staging without issue

Le mar. 16 avr. 2024 à 01:38, Crazy-bat11 ***@***.***> a
écrit :

**Comment by Crazy-bat11** [comment]
Hi, another question: which of the conversion type option should I use for converting to dosbox-staging and dosbox-pure?

**Comment by Voljega** [comment]
for dosbox-pure : check dosbox-pure
for any other dosbox: uncheck dosbox-pure
