### ISSUE TITLE
Feature request / question: Compatibility with Retrobat / EmulationStation for Windows

### ISSUE THREAD

**Issue by diegopau** [Voljega/ExoDOSConverter#24]
Hi,

I recently discovered the impressive ExoDOS project and this great repo for the ones we prefer any front-end based on EmulationStation.

In my case I am using Retrobat https://www.retrobat.ovh which is basically batocera for Windows, the EmulationStation is the same as in Batocera but with tweaks to work in windows and the repo is here https://github.com/fabricecaruso/batocera-emulationstation/

I think the retrobat community is growing and if this is ever compatible it will be a great addition. Do you think this will be ever possible?

**Comment by Voljega** [comment]
Hello @diegopau,

Well nice coincidence, I just tried Retrobat for the first time yesterday, and already coded the compatibility for it in my tool :)

One slight thing is missing though to make it perfect so I asked a question here and I need the response before committing the compatibility feature : https://retrobat.forumgaming.fr/t261-path-de-lancement-dosbox

**Comment by diegopau** [comment]
wow, very nice, thank you! I think if ExoDOS v5 is about to be released I will wait for that and try it :)
