### ISSUE TITLE
Size of the soft

### ISSUE THREAD

**Issue by soaresden** [Voljega/ExoDOSConverter#25]
Hi, 

The size of the soft don't fit in my 1920*1080 display.
And because we can't resize it, the space of the log inputbox is cropped

**Comment by soaresden** [comment]
![image](https://user-images.githubusercontent.com/54243866/95728077-59adb880-0c7b-11eb-8666-b9d2db5666ff.png)

**Comment by Voljega** [comment]
Hmmm that's pretty strange as it fits well on my 1920*1080

I know of this problem on MacOS but that's the first time I see it on Windows, you are on Windows 10 right ?

**Comment by soaresden** [comment]
Yes, Win10. it can be fixed really easily with reducing the size of the listbox ahead or adding the vertical bar I think

**Comment by Voljega** [comment]
Hmmm I thik the listbox would be less usable like that and adding the vertical bar could be done but would also maybe mess up with the vertical bar of the console part....

Maybe I could reduce the size of the log
One other solution is to reduce the size of the fonts, but this could rendre everything unreadable

It would be better to find the udnerlying issue, is your screen something capable to display more than 1080p maybe ? like a 4K screen or something ?

**Comment by soaresden** [comment]
No, my max is 1920x1080 and i'm on 125%.
Maybe it's that the issue

**Comment by soaresden** [comment]
![image](https://user-images.githubusercontent.com/54243866/95737992-d4310500-0c88-11eb-9d81-9d9c68a94f77.png)
Success !

But I think you can do something on your side

**Comment by Voljega** [comment]
I'm not sure but I'll see what can I do

And you should use a more recent version, 0.5 is already out, and I should release 0.6 which features a ton of improvements before the end of the weekend

**Comment by soaresden** [comment]
thanks you very much, I didn't paid attention to the tag in my adresse bar at first ^^
I'll give it a try then
