### ISSUE TITLE
Better P2K

### ISSUE THREAD

**Issue by soaresden** [Voljega/ExoDOSConverter#27]
here a better template for the p2k file

```
# Recalbox's Pad-to-Keyboard configuration
#GAMENAME GOES HERE
#PLATFORM GOES HERE
 
# DPad and Joystick 1
0:up = up
0:down = down
0:right = right
0:left = left
0:j1up = up
0:j1down = down
0:j1left = left
0:j1right = right

1:up = up
1:down = down
1:right = right
1:left = left
1:j1up = up
1:j1down = down
1:j1left = left
1:j1right = right

# Joystick 2
0:j2up = kp8 ;; Please Edit this with an Action
0:j2down = kp2 ;; Please Edit this with an Action
0:j2left = kp4 ;; Please Edit this with an Action
0:j2right = kp6 ;; Please Edit this with an Action

1:j2up = kp8 ;; Please Edit this with an Action
1:j2down = kp2 ;; Please Edit this with an Action
1:j2left = kp4 ;; Please Edit this with an Action
1:j2right = kp6 ;; Please Edit this with an Action

# Start and Select
0:start = enter ;; Enter Key
0:select = esc ;; Escape Key
1:start = enter ;; Enter Key
1:select = esc ;; Escape Key

# PS Format of the right side controller
# X
0:b = space ;; Please Edit this with an Action
1:b = space ;; Please Edit this with an Action
# O
0:a = leftctrl ;; Please Edit this with an Action
1:a = leftctrl ;; Please Edit this with an Action
# /\
0:x = leftshift ;; Please Edit this with an Action
1:x = leftshift ;; Please Edit this with an Action
# []
0:y = leftalt ;; Please Edit this with an Action
1:y = leftalt ;; Please Edit this with an Action

# L1 and L2
0:l1 = F1 ;; Help
0:l2 = F2 ;; Please Edit this with an Action
1:l1 = F1 ;; Help
1:l2 = F2 ;; Please Edit this with an Action

# R1 and R2
0:r1 = F5 ;; Please Edit this with an Action
0:r2 = b ;; Please Edit this with an Action
1:r1 = F5 ;; Please Edit this with an Action
1:r2 = b ;; Please Edit this with an Action

# L3 and R3
0:l3 = n ;; (N)o
0:r3 = y ;; (Y)es
1:l3 = n ;; (N)o
1:r3 = y ;; (Y)es

#hotkey
0:hotkey = F9 ;; Hotkey + Circle to Exit
````

**Comment by Voljega** [comment]
are you sure with tab key ? shift is much more used among dos games

also hotkey + a to leave game is a pretty meh choice as it doesn't follow convention

**Comment by Voljega** [comment]
also you might want to use L2 and R2 and right stick for mouse

**Comment by soaresden** [comment]
> are you sure with tab key ? shift is much more used among dos games
> 
> also hotkey + a to leave game is a pretty meh choice as it doesn't follow convention

No, you're right, I agree with shift 👍 
Hotley + start on recalbox is the normal thing
Hotkey + O (A) is reset. Because of the CTRL assign to O, it would be strange to put it on start because of "enter". So i think it's good to keep like this

The mouse is not integrated ? How can you emulate these ? I'm very curious if you manage that !

**Comment by Voljega** [comment]
Oh yeah didn't think that the mouse was not integrated in p2k

Well you can do that through the dosbox mapper, but it's compatible with the use of p2k which is much better... (dosbox mapper is linked to one controller)

for left shift the key is `leftshift` right ?

**Comment by Voljega** [comment]
and if you can configure two keys on the same button with p2k, you could always have both ctrl and F9 on hotkey, ça woudl allow you to quit the game with just hotkey

**Comment by soaresden** [comment]
> Oh yeah didn't think that the mouse was not integrated in p2k
> 
> Well you can do that through the dosbox mapper, but it's compatible with the use of p2k which is much better... (dosbox mapper is linked to one controller)
> 
> for left shift the key is `leftshift` right ?

yes, here an image of the controls
![z-P2K-layout-v2](https://user-images.githubusercontent.com/54243866/95998483-32025000-0e35-11eb-8610-f8934d714da5.png)

actually you can't put combos, maybe in the future ? I heard on discord that it's planned to emulate the mouse

**Comment by Voljega** [comment]
on Recalbox discord ?
emulate the mouse with p2k or in dosbox ?

**Comment by soaresden** [comment]
Actually it was on a twitch live, I asked ;)
yes the mouse in p2k, if there is a mouse or a keyboard in usb, it's already Ok
