### ISSUE TITLE
Handle retropie dos folder format

### ISSUE THREAD

**Issue by Voljega** [Voljega/ExoDOSConverter#6]
It seems it is not the same as some other distributions

**Comment by wholee** [comment]
Hi,

I already left a comment on the RetroPie forums, so this is for reference only.

https://retropie.org.uk/docs/PC/
http://dosonthepi.blogspot.com/2015/02/dosbox-configuration-for-individual.html
This is a good starting point to see how RetroPie is dealing with DOS games.
