### ISSUE TITLE
Discworld II fix

### ISSUE THREAD

**Issue by rimsky82** [Voljega/ExoDOSConverter#60]
Discworld II can be fixed by removing the "[" from the renamed iso images.

**Comment by Voljega** [comment]
So the generation was ok but the game wasn't launching without this fix ?

**Comment by rimsky82** [comment]
Correct.  There was no error during generation, I just had to remove the bracket from the iso names and edit the conf accordingly.

**Comment by Voljega** [comment]
Will try to remove brackets on cd names in a next update

**Comment by synrais** [comment]
Soldiers of Fortune (THECHAOS) The Chaos Engine also does this with its cue/bin.

These are the only 2 cd title containing [] in their names.

**Comment by Voljega** [comment]
Thanks @synrais will help for testing
