### ISSUE TITLE
Incorrect Batch line endings when converting using Linux

### ISSUE THREAD

**Issue by cognitivegears** [Voljega/ExoDOSConverter#61]
When running the converter with Linux for MiSTer, all of the batch scripts are saved with unix line endings instead of DOS line endings.  This causes launch failures.  Using EDIT and re-saving each batch files on DOS makes them work.

For example, this is what the files look like before resaving under DOS:

type 1_START.BAT

    cd zorkzero
               zorkzero

Really, it looks like they are missing the line ending \r for DOS to recognize the line endings.

**Comment by Voljega** [comment]
OK I see, I will try to tackle that.

**Comment by cognitivegears** [comment]
Went ahead and created a PR to fix it.
