### ISSUE TITLE
Gunship 2000 (CD-ROM Edition) (1993) 

### ISSUE THREAD

**Issue by synrais** [Voljega/ExoDOSConverter#64]
An extra imgmount command is used which shouldn't be here

**Comment by synrais** [comment]
This was an issue with 5.1 update.
The update files do not get applied until a game is installed or played. 
The .iso that could not be found was not present in 5.0, but is in the update folder of 5.1

**Comment by Voljega** [comment]
yes I didn't code the update for taking the ExoDOS updater into account yet
