### ISSUE TITLE
Errors not logged

### ISSUE THREAD

**Issue by synrais** [Voljega/ExoDOSConverter#65]
During the conversion of 5.1 I noticed a red error that did not end up being logged.

The converter could not find a replacement string for a line in a games config file and threw an error.

 Sorry I cannot remember the game name as I was hoping it would log. 

I can only remember the -a in the string.
 
 It is not a 5.1 related game I made sure of that. The same error should throw on a v5.

**Comment by Voljega** [comment]
Closing this as those errors are less critical errors not meant to appear in general logs, and most should be fixed by now
Don't hesitate to open a more specific issue if you encounter one and have the main console log extract for it though !

Thanks
