### ISSUE TITLE
Upgrade TDLIndexer for better shortname generation

### ISSUE THREAD

**Issue by Voljega** [Voljega/ExoDOSConverter#67]
So a small change but has huge potential.  Working with kudgel, he changed the TDLIndexer used for Total Dos launcher index creation to use the https://raw.githubusercontent.com/Voljega/ExoDOSConverter/master/data/eXoDOSv5.csv as a base for all shortname creation instead of the generic cononical name mapping.
Here is that Pull request.  https://github.com/MobyGamer/total-dos-launcher/pull/47

What this allows is for consistent folder names no matter the pack, or how many games are in the pack.  This then allows for update scripts to know exactly where the games will be so new run.bat files, config files, ini files, game patches can be pushed to packs generated after the fact.
Like my Top 300 Updates script.  But you could do that with any pack generated once this TDLIndexer is implemented.  Can you review the changes and add it?
If User1 generates a Top300 including KingsQuest1,3,5,7 and User2 generates a pack using Kingsquest2,3,4,5 then the old way of generating the short folder names would be the same name but different games.  Doing it this way and using your csv allows for a consistant base no matter the game count.  So update packs can be generated off of a single large github repo and all it does is scan that directory for the games in the pack and send update scripts down for only those games.

**Comment by Voljega** [comment]
Fixed / Done

**Comment by flynnsbit** [comment]
Thank you!!
